simulation:
  time-steps: 100
  chance-gen-self-driven-vehicle: 0.1
  chance-gen-human-driven-vehicle: 0.2
vehicle:
  self-driven:
    initial-speed: 2
    safe-follow: 2
    acceleration: 1
  human-driven:
    initial-speed: 1
    safe-follow: 3
    acceleration: 1
highway:
  self-driving-lane:
    count: 1
    speed-limit: 2
  shared-lane:
    count: 4
    speed-limit: 1
  entry-points:
  - 24
  # - 74
  length: 50
